name: Docker Build & Push

on:
  push:
    tags:
      - 'v*'  # 匹配所有v开头的标签，如v1.0.0

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: e-larex/bililiverecorder-exporter
  IMAGE_NAME: ${{ toLower(format('{0}/{1}', github.repository_owner, github.event.repository.name)) }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract tag version
        id: tag-extractor
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/}
          echo "Extracted tag: $TAG_VERSION"
          echo "tag_version=$TAG_VERSION" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag-extractor.outputs.tag_version }}
          labels: |
            org.opencontainers.image.version=${{ steps.tag-extractor.outputs.tag_version }}
